name: third task

on:
   push:
      branches:
            - main


jobs:
      lint:
            runs-on: ubuntu-24.04
            steps:
                  - run: echo "lint running"
      
      test:
            runs-on: ubuntu-24.04
            strategy:
                  matrix:
                        node-version: [22, 24]
            steps:
                  - uses: actions/checkout@v4
                  - uses: actions/setup-node@v4
                    with:
                        node-version: ${{ matrix.node-version }}
                  - run: echo "testing app with ${{ matrix.node-version }}"

      deploy:
            runs-on: ubuntu-24.04
            needs: [lint, test]
            steps:
                  - run: echo "first two stages successful"
